# a mybinder.org-ready environment for demoing jupyter-fs
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyter-fs-demo
#
name: jupyter-fs-demo

channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.13
  - jupyterlab >=4,<5
  - nodejs >=22,<25
  - pip
  - wheel
